"""empty message

Revision ID: d33af4bfb23d
Revises: f9ef2f99a0d1
Create Date: 2026-06-14 22:20:17.125990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd33af4bfb23d'
down_revision: Union[str, Sequence[str], None] = 'f9ef2f99a0d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('url_clicks',
    sa.Column('url_click_id', sa.Uuid(), nullable=False),
    sa.Column('link_url_id', sa.Uuid(), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('clicked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['link_url_id'], ['link_urls.link_url_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('url_click_id')
    )
    op.create_index('idx_click_url_time', 'url_clicks', ['link_url_id', sa.literal_column('clicked_at DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_click_url_time', table_name='url_clicks')
    op.drop_table('url_clicks')
    # ### end Alembic commands ###
