"""added the urls models

Revision ID: f9ef2f99a0d1
Revises: 3bd26dd595bb
Create Date: 2026-06-14 20:46:49.870209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9ef2f99a0d1'
down_revision: Union[str, Sequence[str], None] = '3bd26dd595bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('link_urls',
    sa.Column('link_url_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('long_url', sa.String(), nullable=False),
    sa.Column('short_code', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('link_url_id'),
    sa.UniqueConstraint('short_code')
    )
    op.create_index('idx_link_expires_at', 'link_urls', ['expires_at'], unique=False)
    op.create_index('idx_user_active_created', 'link_urls', ['user_id', 'is_active', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_user_long_url', 'link_urls', ['user_id', 'long_url'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_user_long_url', table_name='link_urls')
    op.drop_index('idx_user_active_created', table_name='link_urls')
    op.drop_index('idx_link_expires_at', table_name='link_urls')
    op.drop_table('link_urls')
    # ### end Alembic commands ###
